### ISSUE TITLE
Set username and pwd 

### ISSUE THREAD

**Issue by sysxda** [nnjun/SimpleOpenVpn-Android#1]
Is there is any way to add username and password to this app ?

**Comment by nnjun** [comment]
You just need to configure it on the server. Search for "OpenVpn Settings Password Login" for specific settings.------------------ 原始邮件 ------------------
发件人: "Stanislav Bukovetsiy"<notifications@github.com>
发送时间: 2019年8月10日(星期六) 晚上11:43
收件人: "nnjun/SimpleOpenVpn-Android"<SimpleOpenVpn-Android@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [nnjun/SimpleOpenVpn-Android] Set username and pwd  (#1)



Is there is any way to add username and password to this app ?
 
&mdash;

**Comment by sysxda** [comment]
Big thanks for hard work

**Comment by sysxda** [comment]
https://github.com/nnjun/SimpleOpenVpn-Android/blob/c5b8a38ce28b1eac7a04a60a840d489ef66e3a7d/server/src/main/java/de/blinkt/openvpn/VpnProfile.java#L125 

https://github.com/nnjun/SimpleOpenVpn-Android/blob/c5b8a38ce28b1eac7a04a60a840d489ef66e3a7d/server/src/main/java/de/blinkt/openvpn/VpnProfile.java#L126

you mean this ?

**Comment by nnjun** [comment]
Yes, you're right. If your server is configured and supports password login, then we can set the password by "loadVpnProfile (data);" and then "getVpnProfile (). mUserName" and "getVpnProfile (). mPassword". If you still encounter problems, I can provide configuration for your reference tomorrow.

**Comment by sysxda** [comment]
yep , its still not working for me :( getting auth message at all when it disconnects ...

**Comment by nnjun** [comment]
If you cancel your account password, can you connect successfully?

**Comment by sysxda** [comment]
nope :( getting logs 

`08-10 20:04:57.781 I/OpenVPN (15954): Starting openvpn
08-10 20:04:59.305 I/OpenVPN (15954): OpenVPN process exited
08-10 20:04:59.305 D/TAG     (15954): 连接关闭
08-10 20:04:59.331 I/OpenVPN (15954): Exiting
`

**Comment by nnjun** [comment]
Did you build the server yourself?

**Comment by sysxda** [comment]
Yes , im can give my config , its working in another openvpnapp

https://github.com/micer/openvpn-sample-app
б, 10 авг. 2019 г., 20:15 Milk <notifications@github.com>:

**Comment by coderzstas** [comment]
Yes

**Comment by nnjun** [comment]
I'm not sure if it's because of your server configuration that you can't connect. There's a public service provider here. You can choose from it to download the ovpn file and try to connect. Servers may be unavailable or overcrowded. Please change other attempts! If it still fails, please leave a message. I wake up and reply. Good luck to you brother!

https://www.vpngate.net/cn/

**Comment by nnjun** [comment]
Okay, I'll try to find out why!

**Comment by nnjun** [comment]
Hello friend, today after my verification is no problem. Here you need to configure something, and I'll try to provide it to you. First of all, for the convenience of my scripted server, the open source address is:[https://github.com/Nyr/openvpn-install](https://github.com/Nyr/openvpn-install). Of course, self-built is also possible!

Step 1.
We need to make special configuration for "/ etc/openvpn/server/server.conf", first we need to add the following at the bottom.

```
script-security 3
auth-user-pass-verify /etc/openvpn/server/check.sh via-env
client-cert-not-required
username-as-common-name
```

Step 2.
Customers need to add a sentence to ovpn: "auth-user-pass"

APP：
![image](https://user-images.githubusercontent.com/26114387/62831383-d183eb80-bc50-11e9-93ae-a4e749ce33f3.png)


Additional notes：
The "psw-file" file represents the user's account password, which is preceded by an account, followed by a password, separated by a space in the middle. For example: 123 456.Granting permission 660

"check. sh" is a script to verify the password. You just need to change the log path and the location of "psw-file" of your output. The rest is unchanged.Granting permission +x 

If everything goes well, the server will output when the user connects:
```
Sun Aug 11 15:34:54 2019 61.144.97.186:47490 peer info: IV_VER=2.4_master
Sun Aug 11 15:34:54 2019 61.144.97.186:47490 peer info: IV_PLAT=android
Sun Aug 11 15:34:54 2019 61.144.97.186:47490 peer info: IV_PROTO=2
Sun Aug 11 15:34:54 2019 61.144.97.186:47490 peer info: IV_NCP=2
Sun Aug 11 15:34:54 2019 61.144.97.186:47490 peer info: IV_LZ4=1
Sun Aug 11 15:34:54 2019 61.144.97.186:47490 peer info: IV_LZ4v2=1
Sun Aug 11 15:34:54 2019 61.144.97.186:47490 peer info: IV_LZO=1
Sun Aug 11 15:34:54 2019 61.144.97.186:47490 peer info: IV_COMP_STUB=1
Sun Aug 11 15:34:54 2019 61.144.97.186:47490 peer info: IV_COMP_STUBv2=1
Sun Aug 11 15:34:54 2019 61.144.97.186:47490 peer info: IV_RGI6=1
Sun Aug 11 15:34:54 2019 61.144.97.186:47490 peer info: IV_GUI_VER=com.app.vpn_1.0
Sun Aug 11 15:34:54 2019 61.144.97.186:47490 TLS: Username/Password authentication succeeded for username '123' [CN SET]
```

If the password is wrong, the server will output：
```
Sun Aug 11 15:51:46 2019 61.144.97.186:48946 peer info: IV_VER=2.4_master
Sun Aug 11 15:51:46 2019 61.144.97.186:48946 peer info: IV_PLAT=android
Sun Aug 11 15:51:46 2019 61.144.97.186:48946 peer info: IV_PROTO=2
Sun Aug 11 15:51:46 2019 61.144.97.186:48946 peer info: IV_NCP=2
Sun Aug 11 15:51:46 2019 61.144.97.186:48946 peer info: IV_LZ4=1
Sun Aug 11 15:51:46 2019 61.144.97.186:48946 peer info: IV_LZ4v2=1
Sun Aug 11 15:51:46 2019 61.144.97.186:48946 peer info: IV_LZO=1
Sun Aug 11 15:51:46 2019 61.144.97.186:48946 peer info: IV_COMP_STUB=1
Sun Aug 11 15:51:46 2019 61.144.97.186:48946 peer info: IV_COMP_STUBv2=1
Sun Aug 11 15:51:46 2019 61.144.97.186:48946 peer info: IV_RGI6=1
Sun Aug 11 15:51:46 2019 61.144.97.186:48946 peer info: IV_GUI_VER=com.app.vpn_1.0
Sun Aug 11 15:51:46 2019 61.144.97.186:48946 WARNING: Failed running command (--auth-user-pass-verify): external program exited with error status: 1
Sun Aug 11 15:51:46 2019 61.144.97.186:48946 TLS Auth Error: Auth Username/Password verification failed for peer
```

I have sent you the required files by mail.
