### ISSUE TITLE
Unable to reconnect

### ISSUE THREAD

**Issue by yunolawliet** [nnjun/SimpleOpenVpn-Android#3]
Hello Milk,

I have an issue regarding the reconnection.
If you are unable to connect to internet (for example you don't have enough balance to do so)
The VPN doesn't reconnect, can we make the VPN try and try and try to reconnect until it does?

Thanks

**Comment by nnjun** [comment]
你是说在没有网络的情况下进行连接，它并不会一直重试吗？

**Comment by nnjun** [comment]
You mean to connect without a network, and it won't be retried all the time?

**Comment by yunolawliet** [comment]
Yes  this scenario is helpful for example you went in a tunnel with no
signal. Nonetheless the default vpn app always tries to reconnect no matter
what.

**Comment by nnjun** [comment]
When I test, I find that I disconnect from the network, and he will prompt "Waition for usable network"

**Comment by yunolawliet** [comment]
Try this scenario,Use a sim card that doesn't have enough balance to connect to the internet. The vpn will then hang. Reconnecting wont work.On Aug 16, 2019 10:55 AM, "SenselessTalk ." <yuno.lawliet@yahoo.com> wrote:Yes  this scenario is helpful for example you went in a tunnel with no signal. Nonetheless the default vpn app always tries to reconnect no matter what.On Fri, Aug 16, 2019, 10:42 AM Milk <notifications@github.com> wrote:You mean to connect without a network, and it won't be retried all the time?

**Comment by nnjun** [comment]
I simulated your scenario and found that the waiting time increased with the number of retries. When I waited for a long time, I saw the prompt "waition 256 seconds between connection attempt", but he was still working. I may need to shorten this time.

**Comment by yunolawliet** [comment]
Also the UI is unresponsive when this happens.

**Comment by yunolawliet** [comment]
You closed the issue again, my friends and I is having this issue, stop
closing issues without resolving them first.

Honestly, I'm done with this wrapper its full of bugs and you  don't even
want to fix it.

**Comment by nnjun** [comment]
Friends, I have work to do. In addition, you said there are many bugs, please let me know. I'll take my spare time to solve it.

**Comment by yunolawliet** [comment]
How can you solve the problems if going to 'closed' all the issue here? 
Again, the wrapper can't handle the reconnection properly, it hangs the UI and just closes instead of reconnecting. But I guess you can't replicate it.

Well, at least you got a wrapper that works only and solely for you and it doesn't for us. LOL
